services:
  database:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database_data:/var/lib/database/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}${DB_PORT}/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}
      DB_PLATFORM: ${DB_PLATFORM}

      DB_PROD_URL: ${DB_PROD_URL}${DB_PROD_PORT}/${DB_PROD_NAME}
      DB_PROD_USERNAME: ${DB_PROD_USER}
      DB_PROD_PASSWORD: ${DB_PROD_PASSWORD}
      DB_PROD_DRIVER: ${DB_PROD_DRIVER}
      DB_PROD_PLATFORM: ${DB_PROD_PLATFORM}

    volumes:
      - ./src:/app/src
      - ./build:/app/build

    depends_on:
      - database
    networks:
      - app_network

    stdin_open: true
    tty: true

volumes:
  database_data:

networks:
  app_network: